### ISSUE TITLE
TB & MDR-TB patient intake form>HIV results>HIV positive patient: rename field "Exam date" for date ART started and CPT started

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mdrtb-dashboard#11]
TB patient intake form>HIV results>HIV positive patient: rename field "Exam date" for date ART started

Task
---------
Rename this text field "Exam date" to "Start date"

**Comment by pwanjiru** [comment]
TB patient intake form>HIV results>HIV positive patient: rename field "Exam date" for date ART started and CPT started

Task
--------
Rename this text field "Exam date" to "Start date"

**Comment by daugmaud** [comment]
Renamed to ART Start Date and CPT Start Date respectively

**Comment by pwanjiru** [comment]
fixed and tested
