### ISSUE TITLE
TB/MDR-TB patient dashboard doesn't display details of the ART and CPT given and dates.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mdrtb-dashboard#12]
TB/MDR-TB patient dashboard doesn't display details of the ART and CPT given and dates.

Task
------
Make this information available in the patient dashboard of the TB or MDR-TB patient

**Comment by daugmaud** [comment]
Am not sure about this, but the dates only appear once you select that a patient has been started on ART/CPT. Kindly clarify the nature of this issue, otherwise test and close

**Comment by pwanjiru** [comment]
Fixed and tested
