### ISSUE TITLE
When enrolling a patient into a program, rename Patient Program to a user friendly name

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mdrtb-dashboard#15]
When enrolling a patient into a program, rename Patient Program to a user friendly name

**Comment by pwanjiru** [comment]
Add  "(TB / MDR TB Case)" to the label for patient program

**Comment by daugmaud** [comment]
There is no space to add "(TB / MDR TB Case)", can we make this a training issue instead? Or suggest a better name instead of Patient Program. Cc @ndisha
