### ISSUE TITLE
For examinations(TB & MDR-TB), rearrange to have examination result first then the date below it.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mdrtb-dashboard#18]
For examinations(TB & MDR-TB), rearrange to have examination result first then the date below it.

Task
-------
Rearranging of the items for the examinations to have the examination drop down menu first followed by the exam date.

**Comment by daugmaud** [comment]
This has been done. also, dates appear, when the option isn't <blank> and isn't <not done>
