### ISSUE TITLE
Cannot enroll a patient to a program: System gives error upon enrollment of a patient

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mdrtb-dashboard#19]
Cannot enroll a patient to a program: System gives error upon enrollment of a patient 
![image](https://cloud.githubusercontent.com/assets/19967923/22963206/ba32b538-f362-11e6-92a8-920b598482bc.png)

**Comment by daugmaud** [comment]
Issue with database. Latest database which included the concept "MDRTB SECOND-LINE REGISTRATION DATE"

**Comment by pwanjiru** [comment]
This has been resolved
