### ISSUE TITLE
MDRTB: Include Culture right after GenXpert. Make it configurable in settings.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mdrtb-dashboard#4]
MDRTB: Include Culture right after GenXpert. Make it configurable in settings.

Task

-Add capturing of details for culture right below GenXpert.
-Make this configurable in settings for the various healthcentres

**Comment by daugmaud** [comment]
Doesn't make sense making culture configurable, since it will be a global_property, and database being central, having it will thus mean it reflecting in every facility and not in one facility, for now I think we don't have the option and have it on the dashboard instead.
