### ISSUE TITLE
MDRTB: On registration of a patient, registration group should have all the content that we currently have for treatment options.

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mdrtb-dashboard#5]
On enrollment of a patient, registration group should have all the content that we currently have for treatment options. The options will be: New, relapse, Return after default, FFT, FRT, TI (N,R,RAD,FFT,FRT,TI)

**Comment by daugmaud** [comment]
Get the latest Database to test this

**Comment by pwanjiru** [comment]
this has been resolved
