### ISSUE TITLE
On Intake form, combine Treatment location and vitals. Rename the tab containing these details

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mdrtb-dashboard#7]
On Intake form, combine Treatment location and vitals. Rename the tab containing these details

**Comment by daugmaud** [comment]
Expound on this. Thought they are already in one tab

**Comment by pwanjiru** [comment]
Hi Dennis,
This was from our last review with you and Ndisha.
I'll close this issue.
